#!/bin/bash
# setup_can.sh
# Sets persistent CAN interface names for the Almond Axol arm CAN bus adapter
# and registers a root crontab @reboot entry to bring up the interfaces.
#
# The Almond Axol adapter (VID 0x1D50 / PID 0x606F) exposes two CAN channels
# on a single USB device:
#   channel 0 (dev_id 0x0) -> can_alm_axol_l  (left arm)
#   channel 1 (dev_id 0x1) -> can_alm_axol_r  (right arm)
#
# Usage: sudo ./setup_can.sh

set -euo pipefail

ALMOND_DIR="${HOME}/.almond"
CAN_DIR="${ALMOND_DIR}/can"
CRON_SCRIPT="${CAN_DIR}/startup.sh"

UDEV_RULES_FILE="/etc/udev/rules.d/90-can.rules"
CAN_L="can_alm_axol_l"
CAN_R="can_alm_axol_r"
VID="1d50"
PID="606f"
BITRATE=1000000
TXQUEUELEN=512

# ── helpers ──────────────────────────────────────────────────────────────────

die() { echo "ERROR: $*" >&2; exit 1; }

require_root() {
    [[ $EUID -eq 0 ]] || die "This script must be run as root (sudo)."
}

# ── step 1: locate the device ─────────────────────────────────────────────────

find_serial() {
    echo "Scanning for Almond Axol CAN adapter (${VID}:${PID})..."

    # Find all net interfaces whose parent USB device matches VID/PID
    local serials=()
    for iface_path in /sys/class/net/can*; do
        [[ -e "$iface_path" ]] || continue
        local vid pid serial
        vid=$(udevadm info -a -p "$iface_path" 2>/dev/null \
              | awk -F'"' '/ATTRS\{idVendor\}/ { print $2; exit }')
        pid=$(udevadm info -a -p "$iface_path" 2>/dev/null \
              | awk -F'"' '/ATTRS\{idProduct\}/ { print $2; exit }')
        if [[ "${vid,,}" == "${VID}" && "${pid,,}" == "${PID}" ]]; then
            serial=$(udevadm info -a -p "$iface_path" 2>/dev/null \
                     | awk -F'"' '/ATTRS\{serial\}/ { print $2; exit }')
            serials+=("$serial")
        fi
    done

    # Deduplicate
    local unique_serials
    mapfile -t unique_serials < <(printf '%s\n' "${serials[@]}" | sort -u)

    if [[ ${#unique_serials[@]} -eq 0 ]]; then
        echo ""
        echo "  No adapter found on bus. If the device is not connected yet,"
        echo "  enter the serial number manually (leave blank to abort):"
        read -rp "  Serial: " SERIAL
        [[ -n "$SERIAL" ]] || die "No serial provided. Connect the device and re-run."
    elif [[ ${#unique_serials[@]} -eq 1 ]]; then
        SERIAL="${unique_serials[0]}"
        echo "  Found adapter — serial: ${SERIAL}"
    else
        echo "  Multiple adapters found:"
        for i in "${!unique_serials[@]}"; do
            echo "    [$i] ${unique_serials[$i]}"
        done
        read -rp "  Select adapter index [0]: " idx
        idx="${idx:-0}"
        SERIAL="${unique_serials[$idx]}"
    fi
}

# ── step 2: write udev rules ──────────────────────────────────────────────────

write_udev_rules() {
    echo "Writing udev rules to ${UDEV_RULES_FILE}..."

    cat > "${UDEV_RULES_FILE}" <<EOF
# Almond Axol dual-channel CAN adapter (generated by enable_can.sh)
# Adapter serial: ${SERIAL}
# Channel 0 -> left arm
SUBSYSTEM=="net", ACTION=="add", ATTRS{idVendor}=="${VID}", ATTRS{idProduct}=="${PID}", ATTRS{serial}=="${SERIAL}", ATTR{dev_id}=="0x0", NAME="${CAN_L}"
# Channel 1 -> right arm
SUBSYSTEM=="net", ACTION=="add", ATTRS{idVendor}=="${VID}", ATTRS{idProduct}=="${PID}", ATTRS{serial}=="${SERIAL}", ATTR{dev_id}=="0x1", NAME="${CAN_R}"
EOF

    echo "  Done."
}

# ── step 3: reload udev ───────────────────────────────────────────────────────

reload_udev() {
    echo "Reloading udev rules..."
    udevadm control --reload-rules
    systemctl restart systemd-udevd
    udevadm trigger
    echo "  Done. Unplug and replug the adapter to apply the new names."
}

# ── step 4: register @reboot cron entry ───────────────────────────────────────

write_cron_script() {
    echo "Writing CAN startup script to ${CRON_SCRIPT}..."
    mkdir -p "${CAN_DIR}"

    cat > "${CRON_SCRIPT}" <<EOF
#!/bin/bash
# Bring up Almond Axol CAN interfaces (generated by enable_can.sh)
set -euo pipefail

for IFACE in ${CAN_L} ${CAN_R}; do
    ip link set "\${IFACE}" down 2>/dev/null || true
    ip link set "\${IFACE}" type can bitrate ${BITRATE}
    ip link set "\${IFACE}" txqueuelen ${TXQUEUELEN}
    ip link set "\${IFACE}" up
done
EOF

    chmod +x "${CRON_SCRIPT}"
    echo "  Done."
}

register_cron() {
    echo "Registering @reboot cron entry in root crontab..."

    local cron_entry="@reboot ${CRON_SCRIPT}"

    # Avoid duplicate entries
    local existing
    existing=$(crontab -l 2>/dev/null || true)

    if echo "${existing}" | grep -qF "${CRON_SCRIPT}"; then
        echo "  Entry already present — skipping."
    else
        (echo "${existing}"; echo "${cron_entry}") | crontab -
        echo "  Added: ${cron_entry}"
    fi
}

# ── main ──────────────────────────────────────────────────────────────────────

require_root
find_serial
write_udev_rules
reload_udev
write_cron_script
register_cron

echo ""
echo "Setup complete."
echo "  Left arm  : ${CAN_L}"
echo "  Right arm : ${CAN_R}"
echo "  Startup   : ${CRON_SCRIPT} (runs at @reboot via root crontab)"
