"""Regenerate the golden vectors that pin ``rust/axol-rt/src/tipdamp.rs`` to
its Python originals (``almond_axol.tuning.imu_damping``,
``almond_axol.tuning.tracking_model.TrackingFilter``, and the solver's FK via
``almond_axol.rt.tipdamp.poe_chain``).

    uv run python scripts/tipdamp_golden.py > rust/axol-rt/src/tipdamp_golden.rs

The inputs are closed-form so the Rust test rebuilds them; only the outputs
are written.
"""

from __future__ import annotations

import math

import numpy as np

from almond_axol.kinematics.solver import KinematicsSolver
from almond_axol.rt.tipdamp import chain_height, poe_chain
from almond_axol.tuning.imu_damping import (
    G,
    EncoderVelocity,
    TipDamper,
    VerticalVelocity,
)
from almond_axol.tuning.tracking_model import TrackingFilter, TrackingModel

IDX = [50, 120, 250, 399, 520, 599]


def arr(xs) -> str:
    return "[" + ", ".join(repr(float(x)) for x in xs) + "]"


def imu_input(k: int):
    t = k * 0.005 + 0.0003 * math.sin(k)
    acc = (
        0.5 * math.sin(2 * math.pi * 0.7 * t),
        0.3 * math.cos(2 * math.pi * 1.3 * t),
        G + 0.2 * math.sin(2 * math.pi * 2.0 * t),
    )
    gyro = (
        20 * math.sin(2 * math.pi * 0.4 * t),
        10 * math.cos(2 * math.pi * 0.9 * t),
        5 * math.sin(2 * math.pi * 1.7 * t),
    )
    return t, acc, gyro


def height_input(k: int):
    t = k / 240.0 + 0.0002 * math.sin(1.3 * k)
    z = 0.05 * math.sin(2 * math.pi * 0.3 * t) + 0.001 * math.sin(2 * math.pi * 3 * t)
    return t, z


def main() -> None:
    out = ["// @generated by scripts/tipdamp_golden.py — do not edit.", ""]
    out.append(f"pub const IDX: [usize; {len(IDX)}] = {arr(IDX).replace('.0', '')};")

    est = VerticalVelocity(hp_hz=0.3, lp_hz=40.0)
    vals = []
    for k in range(600):
        t, acc, gyro = imu_input(k)
        vals.append(est.update(t, np.array(acc), np.array(gyro)))
    out.append(f"pub const VERTICAL: [f64; {len(IDX)}] = {arr(vals[i] for i in IDX)};")

    enc = EncoderVelocity(hp_hz=0.3, lp_hz=40.0, delay_s=0.008)
    vals = []
    for k in range(600):
        t, z = height_input(k)
        vals.append(enc.update(t, z))
    out.append(f"pub const HEIGHT: [f64; {len(IDX)}] = {arr(vals[i] for i in IDX)};")

    model = TrackingModel(1.0059, 14.795, 0.597, 36.217, 0.00363, 0.3, 6.2, 0.07)
    tf = TrackingFilter(model, 240.0)
    xs = [
        0.4 * math.sin(2 * math.pi * 0.5 * k / 240)
        + 0.1 * math.sin(2 * math.pi * 2.2 * k / 240)
        for k in range(600)
    ]
    vals = tf.run(np.array(xs))
    out.append(f"pub const TRACKING: [f64; {len(IDX)}] = {arr(vals[i] for i in IDX)};")

    # The whole damper: lead, notch, per-joint weight and low-pass, clamp.
    d = TipDamper(
        gain=60.0,
        columns=(0, 3),
        max_torque=0.5,
        estimator=VerticalVelocity(hp_hz=0.3, lp_hz=40.0),
        encoder=EncoderVelocity(hp_hz=0.3, lp_hz=40.0, delay_s=0.008),
        lead_hz=8.0,
        weights={3: 0.6},
        notch_hz=11.0,
        notch_q=1.5,
        column_lp={3: 6.0},
    )
    d.start(0.0)
    jac = np.array([-0.4, 0, 0, -0.3, 0, 0, 0])
    taus = []
    j = 0
    for k in range(int(6 * 240)):
        now = k / 240.0
        rows = []
        while j * 0.005 <= now - 0.008:
            t = j * 0.005
            a = -0.002 * (2 * math.pi * 2) ** 2 * math.sin(2 * math.pi * 2 * t)
            rows.append([t, 0.0, 0.0, G + a, 0.0, 0.0, 0.0])
            j += 1
        d.feed_height(now, 0.001 * math.sin(2 * math.pi * 0.25 * now))
        d.feed(np.array(rows).reshape(-1, 7))
        taus.append(d.torque(now, jac))
    tidx = [300, 500, 800, 1100, 1439]
    out.append(
        f"pub const DAMP_IDX: [usize; {len(tidx)}] = {arr(tidx).replace('.0', '')};"
    )
    out.append(
        f"pub const DAMP_S1: [f64; {len(tidx)}] = {arr(taus[i][0] for i in tidx)};"
    )
    out.append(
        f"pub const DAMP_EL: [f64; {len(tidx)}] = {arr(taus[i][3] for i in tidx)};"
    )

    solver = KinematicsSolver()
    chain = poe_chain(solver, "right")
    out.append(f"pub const CHAIN_W: [f64; 21] = {arr(chain['w'].ravel())};")
    out.append(f"pub const CHAIN_R: [f64; 21] = {arr(chain['r'].ravel())};")
    out.append(f"pub const CHAIN_M: [f64; 16] = {arr(chain['m'].ravel())};")
    rng = np.random.default_rng(3)
    poses = rng.uniform(-1.0, 1.0, (4, 7))
    heights, jzs = [], []
    for q in poses:
        full = np.zeros(solver.num_joints, dtype=np.float32)
        full[solver.right_indices] = q
        heights.append(float(solver.ee_positions(full[None])[1][0, 2]))
        jz = []
        for i in range(7):
            qp, qm = q.copy(), q.copy()
            qp[i] += 1e-6
            qm[i] -= 1e-6
            jz.append((chain_height(chain, qp) - chain_height(chain, qm)) / 2e-6)
        jzs.append(jz)
    out.append(f"pub const POSES: [f64; 28] = {arr(poses.ravel())};")
    out.append(f"pub const POSE_HEIGHT: [f64; 4] = {arr(heights)};")
    out.append(f"pub const POSE_JZ: [f64; 28] = {arr(np.ravel(jzs))};")
    print("\n".join(out))


if __name__ == "__main__":
    main()
